server:
  port: 8080

spring:
  mail:
    host: smtp.qq.com
    protocol: smtp
    username: 927038559@qq.com
    password: qyeujrqeepkbbbgb

  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true